#!/usr/bin/env bash

waybar_config_dir="$HOME/.config/waybar"
styles_dir="$HOME/.config/waybar/bars"
config_file="config.jsonc"
style_file="style.css"

menu() {
  options=()
  while IFS= read -r version; do
    options+=("$version")
  done < <(find "$styles_dir" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)

  printf '%s\n' "${options[@]}"
}

refresh_waybar() {
  if pgrep -x "waybar" >/dev/null; then
    pkill -x waybar
    sleep 0.5 # Small delay to ensure clean restart
  fi
  waybar &>/dev/null &
}

main() {
  selected_version=$(menu | rofi -dmenu -config ~/.config/rofi/scripts/waybar/style.rasi -p "Select a version:")

  if [[ -z "$selected_version" ]]; then
    echo "No version selected. Exiting."
    exit 1
  fi

  if [[ ! -d "$styles_dir/$selected_version" ]]; then
    echo "Selected version doesn't exist. Exiting."
    exit 1
  fi

  ln -sf "$styles_dir/$selected_version/$config_file" "$waybar_config_dir/$config_file" &&
    ln -sf "$styles_dir/$selected_version/$style_file" "$waybar_config_dir/$style_file"

  if [[ $? -eq 0 ]]; then
    echo "Configurations updated to $selected_version."
    refresh_waybar
  else
    echo "Failed to update configurations."
    exit 1
  fi
}

main
