#!/usr/bin/env bash

wallpapers_dir="$HOME/Developer/repos/Wallpapers"

build_theme() {
  rows=$1
  cols=$2
  icon_size=$3

  echo "element{orientation:vertical;}element-text{horizontal-align:0.5;}element-icon{size:$icon_size.0000em;}listview{lines:$rows;columns:$cols;}"
}

theme="$HOME/.config/rofi/scripts/wallpaper/style.rasi"

rofi_cmd="rofi -dmenu -i -show-icons -theme-str $(build_theme 5 5 10) -theme ${theme}"

choice=$(
  ls --escape "$wallpapers_dir" | grep -v "README.md" | sort -V |
    while read A; do echo -en "$A\x00icon\x1f$wallpapers_dir/$A\n"; done |
    $rofi_cmd
)

[ -z "$choice" ] && exit 0

wallpaper="$wallpapers_dir/$choice"
SYMLINK_PATH="$HOME/.config/hypr/theme/lock"

if pgrep -x "hyprpaper" >/dev/null; then
  hyprctl hyprpaper reload ,"$wallpaper"
elif pgrep -x "swww" >/dev/null; then
  swww img "$wallpaper" \
    --transition-bezier 0.5,1.19,.8,.4 \
    --transition-type wipe \
    --transition-duration 2 \
    --transition-fps 30
fi

ln -sf "$wallpaper" "$SYMLINK_PATH"

exit 0
