box_art_dir = "/home/eyes/.local/share/icons/games"
hide_entries_without_box_art = false

# Sheepy
[[entries]]
title = "Sheepy: A Short Adventure"
path_box_art = "sheepy.png"

#Eden
# [[entries]]
# title = "Eden"
# launch_command = "/usr/bin/Eden"
# path_box_art = "eden.png"
# path_game_dir = "/mnt/Drive/Eden/games"

# BOTW
[[entries]]
title = "Breath of the Wild"
launch_command = "/usr/bin/Eden \"/mnt/Drive/Eden/games/The Legend of Zelda Breath of the Wild [01007EF00011E000][v0].nsp\""
path_box_art = "botw.png"
path_game_dir = "/mnt/Drive/Eden/games/The Legend of Zelda Breath of the Wild [01007EF00011E000][v0].nsp"

# TOTK
[[entries]]
title = "Tears of the Kingdom"
launch_command = "/usr/bin/Eden \"/mnt/Drive/Eden/games/The Legend of Zelda Tears of the Kingdom [0100F2C0115B6000][v0][US].nsp\""
path_box_art = "totk.png"
path_game_dir = "/mnt/Drive/Eden/games/The Legend of Zelda Tears of the Kingdom [0100F2C0115B6000][v0][US].nsp"
