#!/usr/bin/env bash

# ▄▀█ █▀█ █▀█ █▀
# █▀█ █▀▀ █▀▀ ▄█

# Apps
# thunderbird &
# obsidian &

# Terminal Apps
# $term --class btop btop &
# $term --class nvitop nvitop &
ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false &
