#!/bin/bash

# Automounter for removable media
udiskie &

# Wallpaper Backend
# swww-daemon --format xrgb &
mpvpaper -p DP-1 -o "no-audio --loop" /home/eyes/Videos/Live\ Wallpapers/1.mp4 &

# Pyprland Daemon
pypr --debug /tmp/pypr.log &

# Notification Daemon
swaync &

# OSD Window
swayosd-server &

# Notify about devices connecting and disconnecting
devify &

# Idle daemon to screen lock
hypridle &

# Clipboard
# wl-paste --watch cliphist store &
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &

# Polkit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Screen sharing and portals
"$HOME"/.config/hypr/scripts/portal &
# xwaylandvideobridge & # Off when using Vesktop instead of Discord

# Audio
easyeffects --gapplication-service &

# RGB
openrgb --startminimized -p "Profile 1" &

# Sync
syncthing -no-browser &
