#!/usr/bin/env bash

# Automounter for removable media
udiskie &

# Wallpaper Backend
hyprpaper &
# swww-daemon --format xrgb &
# mpvpaper -f -p &
# $HOME/.config/hypr/scripts/live_wallpaper &

# Pyprland Daemon
pypr --debug /tmp/pypr.log &

# Notification Daemon
swaync &

# OSD Window
swayosd-server &

# Light Filter
hyprsunset &

# Notify about devices connecting and disconnecting
# devify &

# Idle daemon to screen lock
hypridle &

# Clipboard
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &

# Polkit authentication
systemctl --user start hyprpolkitagent &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Screen sharing and portals
$HOME/.config/hypr/scripts/portal &
# xwaylandvideobridge & # Off when using Vesktop instead of Discord

# Audio
easyeffects --gapplication-service &

# Keyboard
kanata -c ~/.config/kanata/config.kbd &

# RGB
openrgb --startminimized -p "Profile 1" &

# Random Wallpaper
sleep 0.4 && $HOME/.config/hypr/scripts/random_wallpaper &

# Light Filter Automation
sleep 0.4 && $HOME/.config/hypr/scripts/sunset &

# Sync
syncthing -no-browser &
