#!/usr/bin/env bash

# █▀ █▀▀ █▀█ █ █ █ █▀▀ █▀▀ █▀
# ▄█ ██▄ █▀▄ ▀▄▀ █ █▄▄ ██▄ ▄█

# Polkit Authentication
systemctl --user start hyprpolkitagent &

# Audio
easyeffects --gapplication-service &

# Screen Lock Idle Daemon
hypridle &

# Kanata
kanata -c $HOME/.config/kanata/config.kdb &

# Pyprland Daemon
pypr --debug /tmp/pypr.log &

# Notification Daemon
swaync &

# Clipboard
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
rm ~/.cache/cliphist/db &

# Removable Media Automounter
udiskie &

# Notify connecting & disconnecting devices
# devify &

# Sync
syncthing -no-browser &

# Screen sharing & Portals
$HOME/.config/hypr/scripts/portal &
# xwaylandvideobridge & # Off when using Vesktop instead of Discord

# Wallpaper Engine
hyprpaper &
# swww-daemon --format xrgb &
sleep 0.6 && $HOME/.config/hypr/scripts/wallpaper &

# Live Wallpaper
# $HOME/.config/hypr/scripts/mpvpaper -i 30 &

# Filter
hyprsunset &
sleep 0.4 && $HOME/.config/hypr/scripts/sunset &
sleep 0.6 && $HOME/.config/hypr/scripts/sunset &

# Bar
# waybar &

# OSD Server
mkfifo "$XDG_RUNTIME_DIR/wob.sock" && tail -f "$XDG_RUNTIME_DIR/wob.sock" | wob &

# RGB
openrgb --startminimized -p "Profile 1" &
