version = 1

[global]
dll = "/mnt/Drive/SteamLibrary/steamapps/common/Lossless Scaling/Lossless.dll"

[[game]]
exe = "benchmark"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "vkcube"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"
