#!/bin/sh
#from lukesmiths dotfiles modified for fzf
# The famous "get a menu of emojis to copy" script.

# Get user selection via fzf from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/bin/emoji | fzf | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	# Directly copy the emoji to clipboard using wl-copy without -selection flag
	printf "$chosen" | wl-copy
	notify-send "'$chosen' copied to clipboard." &
fi
