#!/usr/bin/env bash

DISPLAY="DP-1"
WALLPAPER_DIR="$HOME/Videos/Wallpapers"
SOCKET_PATH="/tmp/mpv-socket"
MPV_OPTIONS="input-ipc-server=$SOCKET_PATH no-audio loop gpu-api=vulkan vo=libmpv hwdec=nvdec vd-lavc-threads=$(nproc)"

change_wallpaper() {
  if [ ! -d "$WALLPAPER_DIR" ]; then
    return 1
  }

  VIDEO_FILES=()
  while IFS= read -r file; do
    VIDEO_FILES+=("$file")
  done < <(find "$WALLPAPER_DIR" -type f \( -name "*.mp4" -o -name "*.mkv" -o -name "*.webm" -o -name "*.avi" -o -name "*.mov" \))

  if [ ${#VIDEO_FILES[@]} -eq 0 ]; then
    return 1
  }

  RANDOM_VIDEO="${VIDEO_FILES[RANDOM % ${#VIDEO_FILES[@]}]}"

  mpvpaper "$DISPLAY" -o "$MPV_OPTIONS" "$RANDOM_VIDEO"
}

change_wallpaper

while true; do
  sleep 1800 # seconds
  change_wallpaper
done
