#!/usr/bin/env bash

active_class=$(hyprctl -j activewindow | jq '.class')
active_class=$(echo "$active_class" | tr -d \")

grep 'workspace' $HOME/.config/hypr/theme/rules.conf | while IFS= read -r line; do
  workspace_value=$(echo "$line" | sed -n -e 's/^.*workspace \([0-9]*\)[ ,].*$/\1/p')
  class_value=$(echo "$line" | sed -n -e 's/^.*class:\s*\(.*\)$/\1/p')
  regex=$class_value

  if [ -n "$workspace_value" ] && [ -n "$class_value" ]; then
    if echo "$active_class" | grep -E "$regex"; then
      hyprctl dispatch movetoworkspace "$workspace_value"
    fi
  fi
done
exit 1
