#!/usr/bin/env bash

color=$(hyprpicker -a)

echo "$color"

if [[ "$color" ]]; then
  image=/tmp/${color}.png
  convert -size 48x48 xc:"$color" "$image"
  notify-send -i "$image" "$color" "Copied to clipboard"
fi
