#!/usr/bin/env bash

DISPLAY="DP-1"
WALLPAPER_DIR="$HOME/Videos/Wallpapers"
THUMBNAILS_DIR="$HOME/.cache/live-wallpapers"
SOCKET_PATH="/tmp/mpv-socket"

mkdir -p "$THUMBNAILS_DIR"

build_theme() {
  rows=$1
  cols=$2
  icon_size=$3

  echo "element{orientation:vertical;}element-text{horizontal-align:0.5;}element-icon{size:$icon_size.0000em;}listview{lines:$rows;columns:$cols;}"
}

generate_thumbnails() {
  for video in "$WALLPAPER_DIR"/*; do
    if [ -f "$video" ]; then
      video_name=$(basename "$video")
      thumbnail_path="$THUMBNAILS_DIR/${video_name}.jpg"

      if [ ! -f "$thumbnail_path" ] || [ "$video" -nt "$thumbnail_path" ]; then
        ffmpeg -y -i "$video" -vframes 1 -ss 00:00:05 "$thumbnail_path" &>/dev/null
      fi
    fi
  done
}

is_mpvpaper_running_with_socket() {
  if pgrep mpvpaper >/dev/null && [ -S "$SOCKET_PATH" ]; then
    return 0 # true
  else
    return 1 # false
  fi
}

change_wallpaper_via_ipc() {
  local video_path="$1"
  echo "loadfile \"$video_path\" replace" | socat - "$SOCKET_PATH"
  return $?
}

generate_thumbnails

THEME="$HOME/.config/rofi/scripts/live-wallpaper/style.rasi"

ROFI_CMD="rofi -dmenu -i -show-icons -theme-str $(build_theme 4 3 12) -theme ${THEME}"

CHOICE=$(
  ls --escape "$WALLPAPER_DIR/" |
    while read A; do
      thumbnail_path="$THUMBNAILS_DIR/${A}.jpg"
      echo -en "$A\x00icon\x1f$thumbnail_path\n"
    done |
    $ROFI_CMD
)

if [ -z "$CHOICE" ]; then
  exit 0
fi

WALLPAPER="$WALLPAPER_DIR/$CHOICE"

CURRENT_WALLPAPER=$(pgrep mpvpaper -a 2>/dev/null | grep -o "/home/.*\.mp4" | head -n 1)

if [ "$WALLPAPER" = "$CURRENT_WALLPAPER" ]; then
  exit 0
else
  if is_mpvpaper_running_with_socket; then
    if change_wallpaper_via_ipc "$WALLPAPER"; then
      exit 0
    fi
  fi

  pkill mpvpaper 2>/dev/null || true

  mpvpaper "$DISPLAY" -o "input-ipc-server=$SOCKET_PATH no-audio loop gpu-api=vulkan vo=libmpv hwdec=nvdec vd-lavc-threads=$(nproc)" "$WALLPAPER"
fi

exit 0
