# Esc
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

# eza
[[manager.prepend_keymap]]
on = "E"
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

[[manager.prepend_keymap]]
on = "-"
run = "plugin eza-preview --args='--inc-level'"
desc = "Increment tree level"

[[manager.prepend_keymap]]
on = "_"
run = "plugin eza-preview --args='--dec-level'"
desc = "Decrement tree level"

[[manager.prepend_keymap]]
on = "$"
run = "plugin eza-preview --args='--toggle-follow-symlinks'"
desc = "Toggle tree follow symlinks"

# preview
[[manager.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'qlmanage -p "$@"'
'''

# hide-preview
[[manager.prepend_keymap]]
on   = "T"
run  = "plugin hide-preview"
desc = "Hide or show preview"

# searchjump
[[manager.prepend_keymap]]
on   = [ "i" ]
run = "plugin searchjump"
desc = "searchjump mode"

# smart-filter
[[manager.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

# ripgrep
[[manager.prepend_keymap]]
on   = [ "f","g" ]
run  = "plugin fg"
desc = "find file by content (fuzzy match)"

[[manager.prepend_keymap]]
on   = [ "f","G" ]
run  = "plugin fg --args='rg'"
desc = "find file by content (ripgrep match)"

[[manager.prepend_keymap]]
on   = [ "f","f" ]
run  = "plugin fg --args='fzf'"
desc = "find file by filename"

# compress
[[manager.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

# lazygit
[[manager.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"
