# Main Options
#remote = "pipewire-0"
fps = 30.0
mouse = true
peaks = "auto"
char_set = "default"
theme = "default"
tab = "playback"
max_volume_percent = 100.0
enforce_max_volume = true


# Keybindings
keybindings = [
 { key = { Char = "q" }, action = "Exit" },
 { key = { Char = "m" }, action = "ToggleMute" },
 { key = { Char = "d" }, action = "SetDefault" },
 { key = { Char = "l" }, action = { SetRelativeVolume = 0.01 } },
 { key = "Right", action = { SetRelativeVolume = 0.01 } },
 { key = { Char = "h" }, action = { SetRelativeVolume = -0.01 } },
 { key = "Left", action = { SetRelativeVolume = -0.01 } },
 { key = { Char = "c" }, action = "ActivateDropdown" },
 { key = "Enter", action = "ActivateDropdown" },
 { key = "Esc", action = "CloseDropdown" },
 { key = { Char = "j" }, action = "MoveDown" },
 { key = "Down", action = "MoveDown" },
 { key = { Char = "k" }, action = "MoveUp" },
 { key = "Up", action = "MoveUp" },
 { key = { Char = "L" }, action = "TabRight" },
 { key = "Tab", action = "TabRight" },
 { key = { Char = "H" }, action = "TabLeft" },
 { key = "BackTab", modifiers = "SHIFT", action = "TabLeft" },
 { key = { Char = "`" }, action = { SetAbsoluteVolume = 0.00 } },
 { key = { Char = "1" }, action = { SetAbsoluteVolume = 0.10 } },
 { key = { Char = "2" }, action = { SetAbsoluteVolume = 0.20 } },
 { key = { Char = "3" }, action = { SetAbsoluteVolume = 0.30 } },
 { key = { Char = "4" }, action = { SetAbsoluteVolume = 0.40 } },
 { key = { Char = "5" }, action = { SetAbsoluteVolume = 0.50 } },
 { key = { Char = "6" }, action = { SetAbsoluteVolume = 0.60 } },
 { key = { Char = "7" }, action = { SetAbsoluteVolume = 0.70 } },
 { key = { Char = "8" }, action = { SetAbsoluteVolume = 0.80 } },
 { key = { Char = "9" }, action = { SetAbsoluteVolume = 0.90 } },
 { key = { Char = "0" }, action = { SetAbsoluteVolume = 1.00 } },
 { key = { Char = "?" }, action = "Help" },
]

# Names
[names]
stream = [ "{node:node.name}: {node:media.name}" ]
endpoint = [ "{device:device.nick}", "{node:node.description}" ]
device = [ "{device:device.nick}", "{device:device.description}" ]

# Themes
[themes.default]
default_device = { }
default_stream = { }
selector = { fg = "LightCyan" }
tab = { }
tab_selected = { fg = "LightCyan" }
tab_marker = { fg = "LightCyan" }
list_more = { fg = "DarkGray" }
node_title = { }
node_target = { }
volume = { }
volume_empty = { fg = "DarkGray" }
volume_filled = { fg = "LightBlue" }
meter_inactive = { fg = "DarkGray" }
meter_active = { fg = "LightGreen" }
meter_overload = { fg = "Red" }
meter_center_inactive = { fg = "DarkGray" }
meter_center_active = { fg = "LightGreen" }
config_device = { }
config_profile = { }
dropdown_icon = { }
dropdown_border = { }
dropdown_item = { }
dropdown_selected = { fg = "LightCyan", add_modifier = "REVERSED" }
dropdown_more = { fg = "DarkGray" }
help_border = { }
help_item = { }
help_more = { fg = "DarkGray" }

# Character Sets
[char_sets.default]
default_device = "◇"
default_stream = "◇"
selector_top = "░"
selector_middle = "▒"
selector_bottom = "░"
tab_marker_left = "["
tab_marker_right = "]"
list_more = "•••"
volume_empty = "╌"
volume_filled = "━"
meter_left_inactive = "▮"
meter_left_active = "▮"
meter_left_overload = "▮"
meter_right_inactive = "▮"
meter_right_active = "▮"
meter_right_overload = "▮"
meter_center_left_inactive = "▮"
meter_center_left_active = "▮"
meter_center_right_inactive = "▮"
meter_center_right_active = "▮"
dropdown_icon = "▼"
dropdown_selector = ">"
dropdown_more = "•••"
dropdown_border = "Rounded"
help_more = "•••"
help_border = "Rounded"

# Appendix A
[themes.nocolor]
default_device = { }
default_stream = { }
selector = { add_modifier = "BOLD" }
tab = { }
tab_selected = { add_modifier = "BOLD" }
tab_marker = { add_modifier = "BOLD" }
list_more = { }
node_title = { }
node_target = { }
volume = { }
volume_empty = { add_modifier = "DIM" }
volume_filled = { add_modifier = "BOLD" }
meter_inactive = { add_modifier = "DIM" }
meter_active = { add_modifier = "BOLD" }
meter_overload = { add_modifier = "BOLD" }
meter_center_inactive = { add_modifier = "DIM" }
meter_center_active = { add_modifier = "BOLD" }
config_device = { }
config_profile = { }
dropdown_icon = { }
dropdown_border = { }
dropdown_item = { }
dropdown_selected = { add_modifier = "BOLD | REVERSED" }
dropdown_more = { }
help_border = { }
help_item = { }
help_more = { }

[themes.plain]
default_device = { }
default_stream = { }
selector = { }
tab = { }
tab_selected = { }
tab_marker = { }
list_more = { }
node_title = { }
node_target = { }
volume = { }
volume_empty = { }
volume_filled = { }
meter_inactive = { }
meter_active = { }
meter_overload = { }
meter_center_inactive = { }
meter_center_active = { }
config_device = { }
config_profile = { }
dropdown_icon = { }
dropdown_border = { }
dropdown_item = { }
dropdown_selected = { }
dropdown_more = { }
help_border = { }
help_item = { }
help_more = { }

[char_sets.compat]
default_device = "◊"
default_stream = "◊"
selector_top = "░"
selector_middle = "▒"
selector_bottom = "░"
tab_marker_left = "["
tab_marker_right = "]"
list_more = "•••"
volume_empty = "─"
volume_filled = "━"
meter_left_inactive = "┃"
meter_left_active = "┃"
meter_left_overload = "┃"
meter_right_inactive = "┃"
meter_right_active = "┃"
meter_right_overload = "┃"
meter_center_left_inactive = "█"
meter_center_left_active = "█"
meter_center_right_inactive = "█"
meter_center_right_active = "█"
dropdown_icon = "▼"
dropdown_selector = ">"
dropdown_more = "•••"
dropdown_border = "Plain"
help_more = "•••"
help_border = "Plain"

[char_sets.extracompat]
default_device = "*"
default_stream = "*"
selector_top = "-"
selector_middle = "="
selector_bottom = "-"
tab_marker_left = "["
tab_marker_right = "]"
list_more = "~~~"
volume_empty = "-"
volume_filled = "="
meter_left_inactive = "="
meter_left_active = "#"
meter_left_overload = "!"
meter_right_inactive = "="
meter_right_active = "#"
meter_right_overload = "!"
meter_center_left_inactive = "["
meter_center_left_active = "["
meter_center_right_inactive = "]"
meter_center_right_active = "]"
dropdown_icon = "\\"
dropdown_selector = ">"
dropdown_more = "~~~"
dropdown_border = "Plain"
help_more = "~~~"
help_border = "Plain"
